#include "key.h"

namespace blowbox
{
	//------------------------------------------------------------------------------------------------------
	std::string KeyToString(const BB_KEY_TYPE& key)
	{
		switch (key)
		{
		case BB_KEY_TYPE::BB_KEY_BACKSPACE:			return "Backspace";
		case BB_KEY_TYPE::BB_KEY_TAB:				return "Tab";
		case BB_KEY_TYPE::BB_KEY_CLEAR:				return "Clear";
		case BB_KEY_TYPE::BB_KEY_ENTER:				return "Enter";
		case BB_KEY_TYPE::BB_KEY_SHIFT:				return "Shift";
		case BB_KEY_TYPE::BB_KEY_CONTROL:			return "Control";
		case BB_KEY_TYPE::BB_KEY_ALT:				return "Alt";
		case BB_KEY_TYPE::BB_KEY_PAUSE:				return "Pause";
		case BB_KEY_TYPE::BB_KEY_CAPS_LOCK:			return "Caps Lock";
		case BB_KEY_TYPE::BB_KEY_ESCAPE:			return "Escape";
		case BB_KEY_TYPE::BB_KEY_SPACE:				return "Space";
		case BB_KEY_TYPE::BB_KEY_PAGE_UP:			return "Page Up";
		case BB_KEY_TYPE::BB_KEY_PAGE_DOWN:			return "Page Down";
		case BB_KEY_TYPE::BB_KEY_END:				return "End";
		case BB_KEY_TYPE::BB_KEY_HOME:				return "Home";
		case BB_KEY_TYPE::BB_KEY_LEFT:				return "Left";
		case BB_KEY_TYPE::BB_KEY_UP:				return "Up";
		case BB_KEY_TYPE::BB_KEY_RIGHT:				return "Right";
		case BB_KEY_TYPE::BB_KEY_DOWN:				return "Down";
		case BB_KEY_TYPE::BB_KEY_SELECT:			return "Select";
		case BB_KEY_TYPE::BB_KEY_PRINT:				return "Print";
		case BB_KEY_TYPE::BB_KEY_EXECUTE:			return "Execute";
		case BB_KEY_TYPE::BB_KEY_PRINT_SCREEN:		return "Print Screen";
		case BB_KEY_TYPE::BB_KEY_INSERT:			return "Insert";
		case BB_KEY_TYPE::BB_KEY_DELETE:			return "Delete";
		case BB_KEY_TYPE::BB_KEY_HELP:				return "Help";
		case BB_KEY_TYPE::BB_KEY_ZERO:				return "0";
		case BB_KEY_TYPE::BB_KEY_ONE:				return "1";
		case BB_KEY_TYPE::BB_KEY_TWO:				return "2";
		case BB_KEY_TYPE::BB_KEY_THREE:				return "3";
		case BB_KEY_TYPE::BB_KEY_FOUR:				return "4";
		case BB_KEY_TYPE::BB_KEY_FIVE:				return "5";
		case BB_KEY_TYPE::BB_KEY_SIX:				return "6";
		case BB_KEY_TYPE::BB_KEY_SEVEN:				return "7";
		case BB_KEY_TYPE::BB_KEY_EIGHT:				return "8";
		case BB_KEY_TYPE::BB_KEY_NINE:				return "9";
		case BB_KEY_TYPE::BB_KEY_A:					return "A";
		case BB_KEY_TYPE::BB_KEY_B:					return "B";
		case BB_KEY_TYPE::BB_KEY_C:					return "C";
		case BB_KEY_TYPE::BB_KEY_D:					return "D";
		case BB_KEY_TYPE::BB_KEY_E:					return "E";
		case BB_KEY_TYPE::BB_KEY_F:					return "F";
		case BB_KEY_TYPE::BB_KEY_G:					return "G";
		case BB_KEY_TYPE::BB_KEY_H:					return "H";
		case BB_KEY_TYPE::BB_KEY_I:					return "I";
		case BB_KEY_TYPE::BB_KEY_J:					return "J";
		case BB_KEY_TYPE::BB_KEY_K:					return "K";
		case BB_KEY_TYPE::BB_KEY_L:					return "L";
		case BB_KEY_TYPE::BB_KEY_M:					return "M";
		case BB_KEY_TYPE::BB_KEY_N:					return "N";
		case BB_KEY_TYPE::BB_KEY_O:					return "O";
		case BB_KEY_TYPE::BB_KEY_P:					return "P";
		case BB_KEY_TYPE::BB_KEY_Q:					return "Q";
		case BB_KEY_TYPE::BB_KEY_R:					return "R";
		case BB_KEY_TYPE::BB_KEY_S:					return "S";
		case BB_KEY_TYPE::BB_KEY_T:					return "T";
		case BB_KEY_TYPE::BB_KEY_U:					return "U";
		case BB_KEY_TYPE::BB_KEY_V:					return "V";
		case BB_KEY_TYPE::BB_KEY_W:					return "W";
		case BB_KEY_TYPE::BB_KEY_X:					return "X";
		case BB_KEY_TYPE::BB_KEY_Y:					return "Y";
		case BB_KEY_TYPE::BB_KEY_Z:					return "Z";
		case BB_KEY_TYPE::BB_KEY_LEFT_WINDOWS_KEY:	return "Left Windows";
		case BB_KEY_TYPE::BB_KEY_RIGHT_WINDOWS_KEY:	return "Right Windows";
		case BB_KEY_TYPE::BB_KEY_APPLICATIONS_KEY:	return "Applications";
		case BB_KEY_TYPE::BB_KEY_SLEEP:				return "Sleep";
		case BB_KEY_TYPE::BB_KEY_NUMPAD0:			return "Numpad0";
		case BB_KEY_TYPE::BB_KEY_NUMPAD1:			return "Numpad1";
		case BB_KEY_TYPE::BB_KEY_NUMPAD2:			return "Numpad2";
		case BB_KEY_TYPE::BB_KEY_NUMPAD3:			return "Numpad3";
		case BB_KEY_TYPE::BB_KEY_NUMPAD4:			return "Numpad4";
		case BB_KEY_TYPE::BB_KEY_NUMPAD5:			return "Numpad5";
		case BB_KEY_TYPE::BB_KEY_NUMPAD6:			return "Numpad6";
		case BB_KEY_TYPE::BB_KEY_NUMPAD7:			return "Numpad7";
		case BB_KEY_TYPE::BB_KEY_NUMPAD8:			return "Numpad8";
		case BB_KEY_TYPE::BB_KEY_NUMPAD9:			return "Numpad9";
		case BB_KEY_TYPE::BB_KEY_MULTIPLY:			return "Multiply";
		case BB_KEY_TYPE::BB_KEY_PLUS:				return "Plus";
		case BB_KEY_TYPE::BB_KEY_SEPERATOR:			return "Seperator";
		case BB_KEY_TYPE::BB_KEY_MINUS:				return "Minus";
		case BB_KEY_TYPE::BB_KEY_DECIMAL:			return "Decimal";
		case BB_KEY_TYPE::BB_KEY_DIVIDE:			return "Divide";
		case BB_KEY_TYPE::BB_KEY_F1:				return "F1";
		case BB_KEY_TYPE::BB_KEY_F2:				return "F2";
		case BB_KEY_TYPE::BB_KEY_F3:				return "F3";
		case BB_KEY_TYPE::BB_KEY_F4:				return "F4";
		case BB_KEY_TYPE::BB_KEY_F5:				return "F5";
		case BB_KEY_TYPE::BB_KEY_F6:				return "F6";
		case BB_KEY_TYPE::BB_KEY_F7:				return "F7";
		case BB_KEY_TYPE::BB_KEY_F8:				return "F8";
		case BB_KEY_TYPE::BB_KEY_F9:				return "F9";
		case BB_KEY_TYPE::BB_KEY_F10:				return "F10";
		case BB_KEY_TYPE::BB_KEY_F11:				return "F11";
		case BB_KEY_TYPE::BB_KEY_F12:				return "F12";
		case BB_KEY_TYPE::BB_KEY_F13:				return "F13";
		case BB_KEY_TYPE::BB_KEY_F14:				return "F14";
		case BB_KEY_TYPE::BB_KEY_F15:				return "F15";
		case BB_KEY_TYPE::BB_KEY_F16:				return "F16";
		case BB_KEY_TYPE::BB_KEY_F17:				return "F17";
		case BB_KEY_TYPE::BB_KEY_F18:				return "F18";
		case BB_KEY_TYPE::BB_KEY_F19:				return "F19";
		case BB_KEY_TYPE::BB_KEY_F20:				return "F20";
		case BB_KEY_TYPE::BB_KEY_F21:				return "F21";
		case BB_KEY_TYPE::BB_KEY_F22:				return "F22";
		case BB_KEY_TYPE::BB_KEY_F23:				return "F23";
		case BB_KEY_TYPE::BB_KEY_F24:				return "F24";
		case BB_KEY_TYPE::BB_KEY_NUM_LOCK:			return "Numlock";
		case BB_KEY_TYPE::BB_KEY_SCROLL_LOCK:		return "Scroll Lock";
		case BB_KEY_TYPE::BB_KEY_LEFT_SHIFT:		return "Left Shift";
		case BB_KEY_TYPE::BB_KEY_RIGHT_SHIFT:		return "Right Shift";
		case BB_KEY_TYPE::BB_KEY_LEFT_CONTROL:		return "Left Control";
		case BB_KEY_TYPE::BB_KEY_RIGHT_CONTROL:		return "Right Control";
		case BB_KEY_TYPE::BB_KEY_LEFT_MENU:			return "Left Menu";
		case BB_KEY_TYPE::BB_KEY_RIGHT_MENU:		return "Right Menu";
		case BB_KEY_TYPE::BB_KEY_BROWSER_BACK:		return "Browser Back";
		case BB_KEY_TYPE::BB_KEY_BROWSER_FORWARD:	return "Browser Forward";
		case BB_KEY_TYPE::BB_KEY_BROWSER_REFRESH:	return "Browser Refresh";
		case BB_KEY_TYPE::BB_KEY_BROWSER_STOP:		return "Browser Stop";
		case BB_KEY_TYPE::BB_KEY_BROWSER_SEARCH:	return "Browser Search";
		case BB_KEY_TYPE::BB_KEY_BROWSER_FAVORITES:	return "Browser Fave";
		case BB_KEY_TYPE::BB_KEY_BROWSER_HOME:		return "Browser Home";
		case BB_KEY_TYPE::BB_KEY_VOLUME_MUTE:		return "Volume Mute";
		case BB_KEY_TYPE::BB_KEY_VOLUME_DOWN:		return "Volume Down";
		case BB_KEY_TYPE::BB_KEY_VOLUME_UP:			return "Volume Up";
		case BB_KEY_TYPE::BB_KEY_NEXT_TRACK:		return "Next Track";
		case BB_KEY_TYPE::BB_KEY_PREVIOUS_TRACK:	return "Previous Track";
		case BB_KEY_TYPE::BB_KEY_STOP_MEDIA:		return "Stop Media";
		case BB_KEY_TYPE::BB_KEY_PLAY_PAUSE:		return "Play Pause";
		case BB_KEY_TYPE::BB_KEY_LAUNCH_MAIL:		return "Mail";
		case BB_KEY_TYPE::BB_KEY_SELECT_MEDIA:		return "Select Media";
		case BB_KEY_TYPE::BB_KEY_LAUNCH_APP1:		return "Launch App 1";
		case BB_KEY_TYPE::BB_KEY_LAUNCH_APP2:		return "Launch App 2";
		case BB_KEY_TYPE::BB_KEY_OEM1:				return "OEM1";
		case BB_KEY_TYPE::BB_KEY_OEMPLUS:			return "OEM Plus";
		case BB_KEY_TYPE::BB_KEY_OEMCOMMA:			return "OEM Comma";
		case BB_KEY_TYPE::BB_KEY_OEMMINUS:			return "OEM Minus";
		case BB_KEY_TYPE::BB_KEY_OEMPERIOD:			return "OEM Period";
		case BB_KEY_TYPE::BB_KEY_OEM2:				return "OEM2";
		case BB_KEY_TYPE::BB_KEY_OEM3:				return "OEM3";
		case BB_KEY_TYPE::BB_KEY_OEM4:				return "OEM4";
		case BB_KEY_TYPE::BB_KEY_OEM5:				return "OEM5";
		case BB_KEY_TYPE::BB_KEY_OEM6:				return "OEM6";
		case BB_KEY_TYPE::BB_KEY_OEM7:				return "OEM7";
		case BB_KEY_TYPE::BB_KEY_OEM8:				return "OEM8";
		case BB_KEY_TYPE::BB_KEY_OEM102:			return "OEM102";
		case BB_KEY_TYPE::BB_KEY_PROCESS:			return "Process";
		case BB_KEY_TYPE::BB_KEY_PACKET:			return "Packet";
		case BB_KEY_TYPE::BB_KEY_ATTN:				return "Attn";
		case BB_KEY_TYPE::BB_KEY_CRSEL:				return "CrSel";
		case BB_KEY_TYPE::BB_KEY_EXSEL:				return "ExSel";
		case BB_KEY_TYPE::BB_KEY_ERASEEOF:			return "Erase EOF";
		case BB_KEY_TYPE::BB_KEY_PLAY:				return "Play";
		case BB_KEY_TYPE::BB_KEY_ZOOM:				return "Zoom";
		case BB_KEY_TYPE::BB_KEY_PA1:				return "PA1";
		case BB_KEY_TYPE::BB_KEY_OEMCLEAR:			return "OEM Clear";
		default:									return "None";
		}
	}

	//------------------------------------------------------------------------------------------------------
	char KeyToChar(const BB_KEY_TYPE& key, bool shift, bool caps_lock)
	{
		bool shorthand_shiftcaps_result = (!shift && !caps_lock) || (shift && caps_lock);

		switch (key)
		{
		case BB_KEY_TYPE::BB_KEY_SPACE:				return ' ';
		case BB_KEY_TYPE::BB_KEY_ZERO:				if (!shift) return '0';		else return ')';
		case BB_KEY_TYPE::BB_KEY_ONE:				if (!shift) return '1';		else return '!';
		case BB_KEY_TYPE::BB_KEY_TWO:				if (!shift) return '2';		else return '@';
		case BB_KEY_TYPE::BB_KEY_THREE:				if (!shift) return '3';		else return '#';
		case BB_KEY_TYPE::BB_KEY_FOUR:				if (!shift) return '4';		else return '$';
		case BB_KEY_TYPE::BB_KEY_FIVE:				if (!shift) return '5';		else return '%';
		case BB_KEY_TYPE::BB_KEY_SIX:				if (!shift) return '6';		else return '^';
		case BB_KEY_TYPE::BB_KEY_SEVEN:				if (!shift) return '7';		else return '&';
		case BB_KEY_TYPE::BB_KEY_EIGHT:				if (!shift) return '8';		else return '*';
		case BB_KEY_TYPE::BB_KEY_NINE:				if (!shift) return '9';		else return '(';
		case BB_KEY_TYPE::BB_KEY_A:					if (shorthand_shiftcaps_result) return 'a';		else return 'A';
		case BB_KEY_TYPE::BB_KEY_B:					if (shorthand_shiftcaps_result) return 'b';		else return 'B';
		case BB_KEY_TYPE::BB_KEY_C:					if (shorthand_shiftcaps_result) return 'c';		else return 'C';
		case BB_KEY_TYPE::BB_KEY_D:					if (shorthand_shiftcaps_result) return 'd';		else return 'D';
		case BB_KEY_TYPE::BB_KEY_E:					if (shorthand_shiftcaps_result) return 'e';		else return 'E';
		case BB_KEY_TYPE::BB_KEY_F:					if (shorthand_shiftcaps_result) return 'f';		else return 'F';
		case BB_KEY_TYPE::BB_KEY_G:					if (shorthand_shiftcaps_result) return 'g';		else return 'G';
		case BB_KEY_TYPE::BB_KEY_H:					if (shorthand_shiftcaps_result) return 'h';		else return 'H';
		case BB_KEY_TYPE::BB_KEY_I:					if (shorthand_shiftcaps_result) return 'i';		else return 'I';
		case BB_KEY_TYPE::BB_KEY_J:					if (shorthand_shiftcaps_result) return 'j';		else return 'J';
		case BB_KEY_TYPE::BB_KEY_K:					if (shorthand_shiftcaps_result) return 'k';		else return 'K';
		case BB_KEY_TYPE::BB_KEY_L:					if (shorthand_shiftcaps_result) return 'l';		else return 'L';
		case BB_KEY_TYPE::BB_KEY_M:					if (shorthand_shiftcaps_result) return 'm';		else return 'M';
		case BB_KEY_TYPE::BB_KEY_N:					if (shorthand_shiftcaps_result) return 'n';		else return 'N';
		case BB_KEY_TYPE::BB_KEY_O:					if (shorthand_shiftcaps_result) return 'o';		else return 'O';
		case BB_KEY_TYPE::BB_KEY_P:					if (shorthand_shiftcaps_result) return 'p';		else return 'P';
		case BB_KEY_TYPE::BB_KEY_Q:					if (shorthand_shiftcaps_result) return 'q';		else return 'Q';
		case BB_KEY_TYPE::BB_KEY_R:					if (shorthand_shiftcaps_result) return 'r';		else return 'R';
		case BB_KEY_TYPE::BB_KEY_S:					if (shorthand_shiftcaps_result) return 's';		else return 'S';
		case BB_KEY_TYPE::BB_KEY_T:					if (shorthand_shiftcaps_result) return 't';		else return 'T';
		case BB_KEY_TYPE::BB_KEY_U:					if (shorthand_shiftcaps_result) return 'u';		else return 'U';
		case BB_KEY_TYPE::BB_KEY_V:					if (shorthand_shiftcaps_result) return 'v';		else return 'V';
		case BB_KEY_TYPE::BB_KEY_W:					if (shorthand_shiftcaps_result) return 'w';		else return 'W';
		case BB_KEY_TYPE::BB_KEY_X:					if (shorthand_shiftcaps_result) return 'x';		else return 'X';
		case BB_KEY_TYPE::BB_KEY_Y:					if (shorthand_shiftcaps_result) return 'y';		else return 'Y';
		case BB_KEY_TYPE::BB_KEY_Z:					if (shorthand_shiftcaps_result) return 'z';		else return 'Z';
		case BB_KEY_TYPE::BB_KEY_NUMPAD0:			return '0';
		case BB_KEY_TYPE::BB_KEY_NUMPAD1:			return '1';
		case BB_KEY_TYPE::BB_KEY_NUMPAD2:			return '2';
		case BB_KEY_TYPE::BB_KEY_NUMPAD3:			return '3';
		case BB_KEY_TYPE::BB_KEY_NUMPAD4:			return '4';
		case BB_KEY_TYPE::BB_KEY_NUMPAD5:			return '5';
		case BB_KEY_TYPE::BB_KEY_NUMPAD6:			return '6';
		case BB_KEY_TYPE::BB_KEY_NUMPAD7:			return '7';
		case BB_KEY_TYPE::BB_KEY_NUMPAD8:			return '8';
		case BB_KEY_TYPE::BB_KEY_NUMPAD9:			return '9';
		case BB_KEY_TYPE::BB_KEY_MULTIPLY:			return '*';
		case BB_KEY_TYPE::BB_KEY_PLUS:				return '+';
		case BB_KEY_TYPE::BB_KEY_SEPERATOR:			return 'S';
		case BB_KEY_TYPE::BB_KEY_MINUS:				return '-';
		case BB_KEY_TYPE::BB_KEY_DECIMAL:			return '.';
		case BB_KEY_TYPE::BB_KEY_DIVIDE:			return '/';
		case BB_KEY_TYPE::BB_KEY_OEM1:				if (!shift) return ';';		else return ':';
		case BB_KEY_TYPE::BB_KEY_OEMPLUS:			if (!shift) return '=';		else return '+';
		case BB_KEY_TYPE::BB_KEY_OEMCOMMA:			if (!shift) return ',';		else return '<';
		case BB_KEY_TYPE::BB_KEY_OEMMINUS:			if (!shift) return '-';		else return '_';
		case BB_KEY_TYPE::BB_KEY_OEMPERIOD:			if (!shift) return '.';		else return '>';
		case BB_KEY_TYPE::BB_KEY_OEM2:				if (!shift) return '/';		else return '?';
		case BB_KEY_TYPE::BB_KEY_OEM3:				if (!shift) return '`';		else return '~';
		case BB_KEY_TYPE::BB_KEY_OEM4:				if (!shift) return '[';		else return '{';
		case BB_KEY_TYPE::BB_KEY_OEM5:				if (!shift) return '\\';	else return '|';
		case BB_KEY_TYPE::BB_KEY_OEM6:				if (!shift) return ']';		else return '}';
		case BB_KEY_TYPE::BB_KEY_OEM7:				if (!shift) return '\'';	else return '"';
		case BB_KEY_TYPE::BB_KEY_OEM8:				if (!shift) return '!';		else return '§';
		case BB_KEY_TYPE::BB_KEY_OEM102:			if (!shift) return '>';		else return '<';
		default:									return ' ';
		}
	}

	//------------------------------------------------------------------------------------------------------
	bool IsKeyAChar(const BB_KEY_TYPE& key)
	{
		static bool key_is_char[256];
		static bool initialized = false;

		if (!initialized)
		{
			key_is_char[BB_KEY_BACKSPACE] = false;
			key_is_char[BB_KEY_TAB] = false;
			key_is_char[BB_KEY_CLEAR] = false;
			key_is_char[BB_KEY_ENTER] = false;
			key_is_char[BB_KEY_SHIFT] = false;
			key_is_char[BB_KEY_CONTROL] = false;
			key_is_char[BB_KEY_ALT] = false;
			key_is_char[BB_KEY_PAUSE] = false;
			key_is_char[BB_KEY_CAPS_LOCK] = false;
			key_is_char[BB_KEY_ESCAPE] = false;
			key_is_char[BB_KEY_SPACE] = true;
			key_is_char[BB_KEY_PAGE_UP] = false;
			key_is_char[BB_KEY_PAGE_DOWN] = false;
			key_is_char[BB_KEY_END] = false;
			key_is_char[BB_KEY_HOME] = false;
			key_is_char[BB_KEY_LEFT] = false;
			key_is_char[BB_KEY_UP] = false;
			key_is_char[BB_KEY_RIGHT] = false;
			key_is_char[BB_KEY_DOWN] = false;
			key_is_char[BB_KEY_SELECT] = false;
			key_is_char[BB_KEY_PRINT] = false;
			key_is_char[BB_KEY_EXECUTE] = false;
			key_is_char[BB_KEY_PRINT_SCREEN] = false;
			key_is_char[BB_KEY_INSERT] = false;
			key_is_char[BB_KEY_DELETE] = false;
			key_is_char[BB_KEY_HELP] = false;
			key_is_char[BB_KEY_ZERO] = true;
			key_is_char[BB_KEY_ONE] = true;
			key_is_char[BB_KEY_TWO] = true;
			key_is_char[BB_KEY_THREE] = true;
			key_is_char[BB_KEY_FOUR] = true;
			key_is_char[BB_KEY_FIVE] = true;
			key_is_char[BB_KEY_SIX] = true;
			key_is_char[BB_KEY_SEVEN] = true;
			key_is_char[BB_KEY_EIGHT] = true;
			key_is_char[BB_KEY_NINE] = true;
			key_is_char[BB_KEY_A] = true;
			key_is_char[BB_KEY_B] = true;
			key_is_char[BB_KEY_C] = true;
			key_is_char[BB_KEY_D] = true;
			key_is_char[BB_KEY_E] = true;
			key_is_char[BB_KEY_F] = true;
			key_is_char[BB_KEY_G] = true;
			key_is_char[BB_KEY_H] = true;
			key_is_char[BB_KEY_I] = true;
			key_is_char[BB_KEY_J] = true;
			key_is_char[BB_KEY_K] = true;
			key_is_char[BB_KEY_L] = true;
			key_is_char[BB_KEY_M] = true;
			key_is_char[BB_KEY_N] = true;
			key_is_char[BB_KEY_O] = true;
			key_is_char[BB_KEY_P] = true;
			key_is_char[BB_KEY_Q] = true;
			key_is_char[BB_KEY_R] = true;
			key_is_char[BB_KEY_S] = true;
			key_is_char[BB_KEY_T] = true;
			key_is_char[BB_KEY_U] = true;
			key_is_char[BB_KEY_V] = true;
			key_is_char[BB_KEY_W] = true;
			key_is_char[BB_KEY_X] = true;
			key_is_char[BB_KEY_Y] = true;
			key_is_char[BB_KEY_Z] = true;
			key_is_char[BB_KEY_LEFT_WINDOWS_KEY] = false;
			key_is_char[BB_KEY_RIGHT_WINDOWS_KEY] = false;
			key_is_char[BB_KEY_APPLICATIONS_KEY] = false;
			key_is_char[BB_KEY_SLEEP] = false;
			key_is_char[BB_KEY_NUMPAD0] = true;
			key_is_char[BB_KEY_NUMPAD1] = true;
			key_is_char[BB_KEY_NUMPAD2] = true;
			key_is_char[BB_KEY_NUMPAD3] = true;
			key_is_char[BB_KEY_NUMPAD4] = true;
			key_is_char[BB_KEY_NUMPAD5] = true;
			key_is_char[BB_KEY_NUMPAD6] = true;
			key_is_char[BB_KEY_NUMPAD7] = true;
			key_is_char[BB_KEY_NUMPAD8] = true;
			key_is_char[BB_KEY_NUMPAD9] = true;
			key_is_char[BB_KEY_MULTIPLY] = true;
			key_is_char[BB_KEY_PLUS] = true;
			key_is_char[BB_KEY_SEPERATOR] = true;
			key_is_char[BB_KEY_MINUS] = true;
			key_is_char[BB_KEY_DECIMAL] = true;
			key_is_char[BB_KEY_DIVIDE] = true;
			key_is_char[BB_KEY_F1] = false;
			key_is_char[BB_KEY_F2] = false;
			key_is_char[BB_KEY_F3] = false;
			key_is_char[BB_KEY_F4] = false;
			key_is_char[BB_KEY_F5] = false;
			key_is_char[BB_KEY_F6] = false;
			key_is_char[BB_KEY_F7] = false;
			key_is_char[BB_KEY_F8] = false;
			key_is_char[BB_KEY_F9] = false;
			key_is_char[BB_KEY_F10] = false;
			key_is_char[BB_KEY_F11] = false;
			key_is_char[BB_KEY_F12] = false;
			key_is_char[BB_KEY_F13] = false;
			key_is_char[BB_KEY_F14] = false;
			key_is_char[BB_KEY_F15] = false;
			key_is_char[BB_KEY_F16] = false;
			key_is_char[BB_KEY_F17] = false;
			key_is_char[BB_KEY_F18] = false;
			key_is_char[BB_KEY_F19] = false;
			key_is_char[BB_KEY_F20] = false;
			key_is_char[BB_KEY_F21] = false;
			key_is_char[BB_KEY_F22] = false;
			key_is_char[BB_KEY_F23] = false;
			key_is_char[BB_KEY_F24] = false;
			key_is_char[BB_KEY_NUM_LOCK] = false;
			key_is_char[BB_KEY_SCROLL_LOCK] = false;
			key_is_char[BB_KEY_LEFT_SHIFT] = false;
			key_is_char[BB_KEY_RIGHT_SHIFT] = false;
			key_is_char[BB_KEY_LEFT_CONTROL] = false;
			key_is_char[BB_KEY_RIGHT_CONTROL] = false;
			key_is_char[BB_KEY_LEFT_MENU] = false;
			key_is_char[BB_KEY_RIGHT_MENU] = false;
			key_is_char[BB_KEY_BROWSER_BACK] = false;
			key_is_char[BB_KEY_BROWSER_FORWARD] = false;
			key_is_char[BB_KEY_BROWSER_REFRESH] = false;
			key_is_char[BB_KEY_BROWSER_STOP] = false;
			key_is_char[BB_KEY_BROWSER_SEARCH] = false;
			key_is_char[BB_KEY_BROWSER_FAVORITES] = false;
			key_is_char[BB_KEY_BROWSER_HOME] = false;
			key_is_char[BB_KEY_VOLUME_MUTE] = false;
			key_is_char[BB_KEY_VOLUME_DOWN] = false;
			key_is_char[BB_KEY_VOLUME_UP] = false;
			key_is_char[BB_KEY_NEXT_TRACK] = false;
			key_is_char[BB_KEY_PREVIOUS_TRACK] = false;
			key_is_char[BB_KEY_STOP_MEDIA] = false;
			key_is_char[BB_KEY_PLAY_PAUSE] = false;
			key_is_char[BB_KEY_LAUNCH_MAIL] = false;
			key_is_char[BB_KEY_SELECT_MEDIA] = false;
			key_is_char[BB_KEY_LAUNCH_APP1] = false;
			key_is_char[BB_KEY_LAUNCH_APP2] = false;
			key_is_char[BB_KEY_OEM1] = true;
			key_is_char[BB_KEY_OEMPLUS] = true;
			key_is_char[BB_KEY_OEMCOMMA] = true;
			key_is_char[BB_KEY_OEMMINUS] = true;
			key_is_char[BB_KEY_OEMPERIOD] = true;
			key_is_char[BB_KEY_OEM2] = true;
			key_is_char[BB_KEY_OEM3] = true;
			key_is_char[BB_KEY_OEM4] = true;
			key_is_char[BB_KEY_OEM5] = true;
			key_is_char[BB_KEY_OEM6] = true;
			key_is_char[BB_KEY_OEM7] = true;
			key_is_char[BB_KEY_OEM8] = true;
			key_is_char[BB_KEY_OEM102] = true;
			key_is_char[BB_KEY_PROCESS] = false;
			key_is_char[BB_KEY_PACKET] = false;
			key_is_char[BB_KEY_ATTN] = false;
			key_is_char[BB_KEY_CRSEL] = false;
			key_is_char[BB_KEY_EXSEL] = false;
			key_is_char[BB_KEY_ERASEEOF] = false;
			key_is_char[BB_KEY_PLAY] = false;
			key_is_char[BB_KEY_ZOOM] = false;
			key_is_char[BB_KEY_PA1] = false;
			key_is_char[BB_KEY_OEMCLEAR] = false;
			key_is_char[BB_KEY_NULL] = false;
		}

		return key_is_char[key];
	}

	//------------------------------------------------------------------------------------------------------
	BB_KEY_TYPE StringToKey(const char * name)
	{
		if (strcmp(name, "Backspace") == 0)				return BB_KEY_TYPE::BB_KEY_BACKSPACE;
		if (strcmp(name, "Tab") == 0)					return BB_KEY_TYPE::BB_KEY_TAB;
		if (strcmp(name, "Clear") == 0)					return BB_KEY_TYPE::BB_KEY_CLEAR;
		if (strcmp(name, "Enter") == 0)					return BB_KEY_TYPE::BB_KEY_ENTER;
		if (strcmp(name, "Shift") == 0)					return BB_KEY_TYPE::BB_KEY_SHIFT;
		if (strcmp(name, "Control") == 0)				return BB_KEY_TYPE::BB_KEY_CONTROL;
		if (strcmp(name, "Alt") == 0)					return BB_KEY_TYPE::BB_KEY_ALT;
		if (strcmp(name, "Pause") == 0)					return BB_KEY_TYPE::BB_KEY_PAUSE;
		if (strcmp(name, "Caps Lock") == 0)				return BB_KEY_TYPE::BB_KEY_CAPS_LOCK;
		if (strcmp(name, "Escape") == 0)				return BB_KEY_TYPE::BB_KEY_ESCAPE;
		if (strcmp(name, "Space") == 0)					return BB_KEY_TYPE::BB_KEY_SPACE;
		if (strcmp(name, "Page Up") == 0)				return BB_KEY_TYPE::BB_KEY_PAGE_UP;
		if (strcmp(name, "Page Down") == 0)				return BB_KEY_TYPE::BB_KEY_PAGE_DOWN;
		if (strcmp(name, "End") == 0)					return BB_KEY_TYPE::BB_KEY_END;
		if (strcmp(name, "Home") == 0)					return BB_KEY_TYPE::BB_KEY_HOME;
		if (strcmp(name, "Left") == 0)					return BB_KEY_TYPE::BB_KEY_LEFT;
		if (strcmp(name, "Up") == 0)					return BB_KEY_TYPE::BB_KEY_UP;
		if (strcmp(name, "Right") == 0)					return BB_KEY_TYPE::BB_KEY_RIGHT;
		if (strcmp(name, "Down") == 0)					return BB_KEY_TYPE::BB_KEY_DOWN;
		if (strcmp(name, "Select") == 0)				return BB_KEY_TYPE::BB_KEY_SELECT;
		if (strcmp(name, "Print") == 0)					return BB_KEY_TYPE::BB_KEY_PRINT;
		if (strcmp(name, "Execute") == 0)				return BB_KEY_TYPE::BB_KEY_EXECUTE;
		if (strcmp(name, "Print Screen") == 0)			return BB_KEY_TYPE::BB_KEY_PRINT_SCREEN;
		if (strcmp(name, "Insert") == 0)				return BB_KEY_TYPE::BB_KEY_INSERT;
		if (strcmp(name, "Delete") == 0)				return BB_KEY_TYPE::BB_KEY_DELETE;
		if (strcmp(name, "Help") == 0)					return BB_KEY_TYPE::BB_KEY_HELP;
		if (strcmp(name, "0") == 0)					    return BB_KEY_TYPE::BB_KEY_ZERO;
		if (strcmp(name, "1") == 0)						return BB_KEY_TYPE::BB_KEY_ONE;
		if (strcmp(name, "2") == 0)						return BB_KEY_TYPE::BB_KEY_TWO;
		if (strcmp(name, "3") == 0)					    return BB_KEY_TYPE::BB_KEY_THREE;
		if (strcmp(name, "4") == 0)					    return BB_KEY_TYPE::BB_KEY_FOUR;
		if (strcmp(name, "5") == 0)					    return BB_KEY_TYPE::BB_KEY_FIVE;
		if (strcmp(name, "6") == 0)						return BB_KEY_TYPE::BB_KEY_SIX;
		if (strcmp(name, "7") == 0)					    return BB_KEY_TYPE::BB_KEY_SEVEN;
		if (strcmp(name, "8") == 0)					    return BB_KEY_TYPE::BB_KEY_EIGHT;
		if (strcmp(name, "9") == 0)					    return BB_KEY_TYPE::BB_KEY_NINE;
		if (strcmp(name, "A") == 0)						return BB_KEY_TYPE::BB_KEY_A;
		if (strcmp(name, "B") == 0)						return BB_KEY_TYPE::BB_KEY_B;
		if (strcmp(name, "C") == 0)						return BB_KEY_TYPE::BB_KEY_C;
		if (strcmp(name, "D") == 0)						return BB_KEY_TYPE::BB_KEY_D;
		if (strcmp(name, "E") == 0)						return BB_KEY_TYPE::BB_KEY_E;
		if (strcmp(name, "F") == 0)						return BB_KEY_TYPE::BB_KEY_F;
		if (strcmp(name, "G") == 0)						return BB_KEY_TYPE::BB_KEY_G;
		if (strcmp(name, "H") == 0)						return BB_KEY_TYPE::BB_KEY_H;
		if (strcmp(name, "I") == 0)						return BB_KEY_TYPE::BB_KEY_I;
		if (strcmp(name, "J") == 0)						return BB_KEY_TYPE::BB_KEY_J;
		if (strcmp(name, "K") == 0)						return BB_KEY_TYPE::BB_KEY_K;
		if (strcmp(name, "L") == 0)						return BB_KEY_TYPE::BB_KEY_L;
		if (strcmp(name, "M") == 0)						return BB_KEY_TYPE::BB_KEY_M;
		if (strcmp(name, "N") == 0)						return BB_KEY_TYPE::BB_KEY_N;
		if (strcmp(name, "O") == 0)						return BB_KEY_TYPE::BB_KEY_O;
		if (strcmp(name, "P") == 0)						return BB_KEY_TYPE::BB_KEY_P;
		if (strcmp(name, "Q") == 0)						return BB_KEY_TYPE::BB_KEY_Q;
		if (strcmp(name, "R") == 0)						return BB_KEY_TYPE::BB_KEY_R;
		if (strcmp(name, "S") == 0)						return BB_KEY_TYPE::BB_KEY_S;
		if (strcmp(name, "T") == 0)						return BB_KEY_TYPE::BB_KEY_T;
		if (strcmp(name, "U") == 0)						return BB_KEY_TYPE::BB_KEY_U;
		if (strcmp(name, "V") == 0)						return BB_KEY_TYPE::BB_KEY_V;
		if (strcmp(name, "W") == 0)						return BB_KEY_TYPE::BB_KEY_W;
		if (strcmp(name, "X") == 0)						return BB_KEY_TYPE::BB_KEY_X;
		if (strcmp(name, "Y") == 0)						return BB_KEY_TYPE::BB_KEY_Y;
		if (strcmp(name, "Z") == 0)						return BB_KEY_TYPE::BB_KEY_Z;
		if (strcmp(name, "Left Windows") == 0)			return BB_KEY_TYPE::BB_KEY_LEFT_WINDOWS_KEY;
		if (strcmp(name, "Right Windows") == 0)			return BB_KEY_TYPE::BB_KEY_RIGHT_WINDOWS_KEY;
		if (strcmp(name, "Applications") == 0)			return BB_KEY_TYPE::BB_KEY_APPLICATIONS_KEY;
		if (strcmp(name, "Sleep") == 0)					return BB_KEY_TYPE::BB_KEY_SLEEP;
		if (strcmp(name, "Numpad0") == 0)				return BB_KEY_TYPE::BB_KEY_NUMPAD0;
		if (strcmp(name, "Numpad1") == 0)				return BB_KEY_TYPE::BB_KEY_NUMPAD1;
		if (strcmp(name, "Numpad2") == 0)				return BB_KEY_TYPE::BB_KEY_NUMPAD2;
		if (strcmp(name, "Numpad3") == 0)				return BB_KEY_TYPE::BB_KEY_NUMPAD3;
		if (strcmp(name, "Numpad4") == 0)				return BB_KEY_TYPE::BB_KEY_NUMPAD4;
		if (strcmp(name, "Numpad5") == 0)				return BB_KEY_TYPE::BB_KEY_NUMPAD5;
		if (strcmp(name, "Numpad6") == 0)				return BB_KEY_TYPE::BB_KEY_NUMPAD6;
		if (strcmp(name, "Numpad7") == 0)				return BB_KEY_TYPE::BB_KEY_NUMPAD7;
		if (strcmp(name, "Numpad8") == 0)				return BB_KEY_TYPE::BB_KEY_NUMPAD8;
		if (strcmp(name, "Numpad9") == 0)				return BB_KEY_TYPE::BB_KEY_NUMPAD9;
		if (strcmp(name, "Multiply") == 0)				return BB_KEY_TYPE::BB_KEY_MULTIPLY;
		if (strcmp(name, "Plus") == 0)					return BB_KEY_TYPE::BB_KEY_PLUS;
		if (strcmp(name, "Seperator") == 0)				return BB_KEY_TYPE::BB_KEY_SEPERATOR;
		if (strcmp(name, "Minus") == 0)					return BB_KEY_TYPE::BB_KEY_MINUS;
		if (strcmp(name, "Decimal") == 0)				return BB_KEY_TYPE::BB_KEY_DECIMAL;
		if (strcmp(name, "Divide") == 0)				return BB_KEY_TYPE::BB_KEY_DIVIDE;
		if (strcmp(name, "F1") == 0)					return BB_KEY_TYPE::BB_KEY_F1;
		if (strcmp(name, "F2") == 0)					return BB_KEY_TYPE::BB_KEY_F2;
		if (strcmp(name, "F3") == 0)					return BB_KEY_TYPE::BB_KEY_F3;
		if (strcmp(name, "F4") == 0)					return BB_KEY_TYPE::BB_KEY_F4;
		if (strcmp(name, "F5") == 0)					return BB_KEY_TYPE::BB_KEY_F5;
		if (strcmp(name, "F6") == 0)					return BB_KEY_TYPE::BB_KEY_F6;
		if (strcmp(name, "F7") == 0)					return BB_KEY_TYPE::BB_KEY_F7;
		if (strcmp(name, "F8") == 0)					return BB_KEY_TYPE::BB_KEY_F8;
		if (strcmp(name, "F9") == 0)					return BB_KEY_TYPE::BB_KEY_F9;
		if (strcmp(name, "F10") == 0)					return BB_KEY_TYPE::BB_KEY_F10;
		if (strcmp(name, "F11") == 0)					return BB_KEY_TYPE::BB_KEY_F11;
		if (strcmp(name, "F12") == 0)					return BB_KEY_TYPE::BB_KEY_F12;
		if (strcmp(name, "F13") == 0)					return BB_KEY_TYPE::BB_KEY_F13;
		if (strcmp(name, "F14") == 0)					return BB_KEY_TYPE::BB_KEY_F14;
		if (strcmp(name, "F15") == 0)					return BB_KEY_TYPE::BB_KEY_F15;
		if (strcmp(name, "F16") == 0)					return BB_KEY_TYPE::BB_KEY_F16;
		if (strcmp(name, "F17") == 0)					return BB_KEY_TYPE::BB_KEY_F17;
		if (strcmp(name, "F18") == 0)					return BB_KEY_TYPE::BB_KEY_F18;
		if (strcmp(name, "F19") == 0)					return BB_KEY_TYPE::BB_KEY_F19;
		if (strcmp(name, "F20") == 0)					return BB_KEY_TYPE::BB_KEY_F20;
		if (strcmp(name, "F21") == 0)					return BB_KEY_TYPE::BB_KEY_F21;
		if (strcmp(name, "F22") == 0)					return BB_KEY_TYPE::BB_KEY_F22;
		if (strcmp(name, "F23") == 0)					return BB_KEY_TYPE::BB_KEY_F23;
		if (strcmp(name, "F24") == 0)					return BB_KEY_TYPE::BB_KEY_F24;
		if (strcmp(name, "Numlock") == 0)				return BB_KEY_TYPE::BB_KEY_NUM_LOCK;
		if (strcmp(name, "Scroll Lock") == 0)			return BB_KEY_TYPE::BB_KEY_SCROLL_LOCK;
		if (strcmp(name, "Left Shift") == 0)			return BB_KEY_TYPE::BB_KEY_LEFT_SHIFT;
		if (strcmp(name, "Right Shift") == 0)			return BB_KEY_TYPE::BB_KEY_RIGHT_SHIFT;
		if (strcmp(name, "Left Control") == 0)			return BB_KEY_TYPE::BB_KEY_LEFT_CONTROL;
		if (strcmp(name, "Right Control") == 0)			return BB_KEY_TYPE::BB_KEY_RIGHT_CONTROL;
		if (strcmp(name, "Left Menu") == 0)				return BB_KEY_TYPE::BB_KEY_LEFT_MENU;
		if (strcmp(name, "Right Menu") == 0)			return BB_KEY_TYPE::BB_KEY_RIGHT_MENU;
		if (strcmp(name, "Browse Back") == 0)			return BB_KEY_TYPE::BB_KEY_BROWSER_BACK;
		if (strcmp(name, "Browse Forward") == 0)		return BB_KEY_TYPE::BB_KEY_BROWSER_FORWARD;
		if (strcmp(name, "Browse Refresh") == 0)		return BB_KEY_TYPE::BB_KEY_BROWSER_REFRESH;
		if (strcmp(name, "Browse Stop") == 0)			return BB_KEY_TYPE::BB_KEY_BROWSER_STOP;
		if (strcmp(name, "Browse Search") == 0)			return BB_KEY_TYPE::BB_KEY_BROWSER_SEARCH;
		if (strcmp(name, "Browse Fave") == 0)			return BB_KEY_TYPE::BB_KEY_BROWSER_FAVORITES;
		if (strcmp(name, "Browse Home") == 0)			return BB_KEY_TYPE::BB_KEY_BROWSER_HOME;
		if (strcmp(name, "Volume Mute") == 0)			return BB_KEY_TYPE::BB_KEY_VOLUME_MUTE;
		if (strcmp(name, "Volume Down") == 0)			return BB_KEY_TYPE::BB_KEY_VOLUME_DOWN;
		if (strcmp(name, "Volume Up") == 0)				return BB_KEY_TYPE::BB_KEY_VOLUME_UP;
		if (strcmp(name, "Next Track") == 0)			return BB_KEY_TYPE::BB_KEY_NEXT_TRACK;
		if (strcmp(name, "Previous Track") == 0)		return BB_KEY_TYPE::BB_KEY_PREVIOUS_TRACK;
		if (strcmp(name, "Stop Media") == 0)			return BB_KEY_TYPE::BB_KEY_STOP_MEDIA;
		if (strcmp(name, "Play Pause") == 0)			return BB_KEY_TYPE::BB_KEY_PLAY_PAUSE;
		if (strcmp(name, "Mail") == 0)					return BB_KEY_TYPE::BB_KEY_LAUNCH_MAIL;
		if (strcmp(name, "Select Media") == 0)			return BB_KEY_TYPE::BB_KEY_SELECT_MEDIA;
		if (strcmp(name, "Launch App 1") == 0)			return BB_KEY_TYPE::BB_KEY_LAUNCH_APP1;
		if (strcmp(name, "Launch App 2") == 0)			return BB_KEY_TYPE::BB_KEY_LAUNCH_APP2;
		if (strcmp(name, "OEM1") == 0)					return BB_KEY_TYPE::BB_KEY_OEM1;
		if (strcmp(name, "OEM Plus") == 0)				return BB_KEY_TYPE::BB_KEY_OEMPLUS;
		if (strcmp(name, "OEM Comma") == 0)				return BB_KEY_TYPE::BB_KEY_OEMCOMMA;
		if (strcmp(name, "OEM Minus") == 0)				return BB_KEY_TYPE::BB_KEY_OEMMINUS;
		if (strcmp(name, "OEM Period") == 0)			return BB_KEY_TYPE::BB_KEY_OEMPERIOD;
		if (strcmp(name, "OEM2") == 0)					return BB_KEY_TYPE::BB_KEY_OEM2;
		if (strcmp(name, "OEM3") == 0)					return BB_KEY_TYPE::BB_KEY_OEM3;
		if (strcmp(name, "OEM4") == 0)					return BB_KEY_TYPE::BB_KEY_OEM4;
		if (strcmp(name, "OEM5") == 0)					return BB_KEY_TYPE::BB_KEY_OEM5;
		if (strcmp(name, "OEM6") == 0)					return BB_KEY_TYPE::BB_KEY_OEM6;
		if (strcmp(name, "OEM7") == 0)					return BB_KEY_TYPE::BB_KEY_OEM7;
		if (strcmp(name, "OEM8") == 0)					return BB_KEY_TYPE::BB_KEY_OEM8;
		if (strcmp(name, "OEM102") == 0)				return BB_KEY_TYPE::BB_KEY_OEM102;
		if (strcmp(name, "Process") == 0)				return BB_KEY_TYPE::BB_KEY_PROCESS;
		if (strcmp(name, "Packet") == 0)				return BB_KEY_TYPE::BB_KEY_PACKET;
		if (strcmp(name, "Attn") == 0)					return BB_KEY_TYPE::BB_KEY_ATTN;
		if (strcmp(name, "CrSel") == 0)					return BB_KEY_TYPE::BB_KEY_CRSEL;
		if (strcmp(name, "ExSel") == 0)					return BB_KEY_TYPE::BB_KEY_EXSEL;
		if (strcmp(name, "Erase EOF") == 0)				return BB_KEY_TYPE::BB_KEY_ERASEEOF;
		if (strcmp(name, "Play") == 0)					return BB_KEY_TYPE::BB_KEY_PLAY;
		if (strcmp(name, "Zoom") == 0)					return BB_KEY_TYPE::BB_KEY_ZOOM;
		if (strcmp(name, "PA1") == 0)					return BB_KEY_TYPE::BB_KEY_PA1;
		if (strcmp(name, "OEM Clear") == 0)				return BB_KEY_TYPE::BB_KEY_OEMCLEAR;

		return BB_KEY_TYPE::BB_KEY_NULL;
	}
	
	//------------------------------------------------------------------------------------------------------
	char ToUpper(char c)
	{
		switch (c)
		{
		case 'a': case 'A': return 'A';
		case 'b': case 'B': return 'B';
		case 'c': case 'C': return 'C';
		case 'd': case 'D': return 'D';
		case 'e': case 'E': return 'E';
		case 'f': case 'F': return 'F';
		case 'g': case 'G': return 'G';
		case 'h': case 'H': return 'H';
		case 'i': case 'I': return 'I';
		case 'j': case 'J': return 'J';
		case 'k': case 'K': return 'K';
		case 'l': case 'L': return 'L';
		case 'm': case 'M': return 'M';
		case 'n': case 'N': return 'N';
		case 'o': case 'O': return 'O';
		case 'p': case 'P': return 'P';
		case 'q': case 'Q': return 'Q';
		case 'r': case 'R': return 'R';
		case 's': case 'S': return 'S';
		case 't': case 'T': return 'T';
		case 'u': case 'U': return 'U';
		case 'v': case 'V': return 'V';
		case 'w': case 'W': return 'W';
		case 'x': case 'X': return 'X';
		case 'y': case 'Y': return 'Y';
		case 'z': case 'Z': return 'Z';
		default: return c;
		}
	}
	
	//------------------------------------------------------------------------------------------------------
	char ToLower(char c)
	{
		switch (c)
		{
		case 'a': case 'A': return 'a';
		case 'b': case 'B': return 'b';
		case 'c': case 'C': return 'c';
		case 'd': case 'D': return 'd';
		case 'e': case 'E': return 'e';
		case 'f': case 'F': return 'f';
		case 'g': case 'G': return 'g';
		case 'h': case 'H': return 'h';
		case 'i': case 'I': return 'i';
		case 'j': case 'J': return 'j';
		case 'k': case 'K': return 'k';
		case 'l': case 'L': return 'l';
		case 'm': case 'M': return 'm';
		case 'n': case 'N': return 'n';
		case 'o': case 'O': return 'o';
		case 'p': case 'P': return 'p';
		case 'q': case 'Q': return 'q';
		case 'r': case 'R': return 'r';
		case 's': case 'S': return 's';
		case 't': case 'T': return 't';
		case 'u': case 'U': return 'u';
		case 'v': case 'V': return 'v';
		case 'w': case 'W': return 'w';
		case 'x': case 'X': return 'x';
		case 'y': case 'Y': return 'y';
		case 'z': case 'Z': return 'z';
		default: return c;
		}
	}
}